name = "thelumenary"
account_id = "211f6ed4e5e21e3964d665afe9216c74"
compatibility_date = "2026-05-25"
pages_build_output_dir = "dist"

[[kv_namespaces]]
binding = "INSIGHT_VOTES"
id = "4abf77f82ed448348f6b673fc893b0c1"
